name: GitHub Classroom Workflow

on: [push]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          node-version: 18
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/checkout@v3     
      - uses: education/autograding@v1
